#!/usr/bin/env bash
# Filename
filename="school"

# Does the file exists
if [[ -e "$filename" ]]; then
    echo "School file exists"
    
    # Not empty?
    if [[ -s "$filename" ]]; then
        echo "School file is not empty"
        
        # Regular file
        if [[ -f "$filename" ]]; then
            echo "School is a regular file"
        fi
    else
        echo "School file is empty"
    fi
else
    echo "School file does not exist"
fi
